services:
  backend:
    build:
      context: backend/
      dockerfile: ./Dockerfile
      target: dev
    container_name: backend
    command: flask --app books run --host 0.0.0.0 --debug
    volumes:
      - ./backend:/app
    networks:
      - backend
    ports:
      - 8000:5000
networks:
  backend:
    name: backend_network
